### ISSUE TITLE
Error 403 & AH01630: client denied by server configuration

### ISSUE THREAD

**Issue by bttrx** [meerkatzenwildschein/shaarli-image-upload#1]
Hi!

I installed your plugin successfully and I can upload images to my Shaarli ver 0.13.0 installation, but I whenever I load the Shaare containing the picture, these two errors are logged:

```
403 GET /data/images/bT7rPQ_xxx.png HTTP/1.0 https://foo.example.com/ Mozilla/5.0 SSL/TLS-Zugriff für Apache
AH01630: client denied by server configuration: /var/www/vhosts/domain.tld/example.com/foo/data/images/bT7rPQ_xxx.png, referer: https://foo.example.com/ Apache-Fehler
```

Same for accessing https://foo.example.com/data/images/bT7rPQ_xxx.png directly.

This is on a shared hosting with Apache+nginx and managed via Plesk.

I already googled around and played with the .htaccess files, but nothing helped so far.
I know, remote diagnostics are difficult, do you have any idea?

For more data, feel free to contact me via https://www.robertriebisch.de/impressum

**Comment by meerkatzenwildschein** [comment]
Hello, 

apart from the .htaccess file, I can only think of two things. Firstly, the apache access configuration (see 
 http://httpd.apache.org/docs/2.4/upgrading.html#access) and the file permissions. But to me it sounds more like configuration. 

To narrow down the problem further, it would be interesting to know whether the image file is accessible in another directory, for example directly in the data directory or even in the root directory. 

If the image is available in the ‘data’ directory, you could also change the path for the images. Simply remove the ‘/images’ in line 49 of the php file. Then the images are not stored in an extra directory, but are located directly in the data directory of the Shaarli installation. However, it would be better to adjust the access configuration so that the ‘images’ directory is accessible.

If you manage to do this, I would be happy to receive feedback and can also improve the installation instructions if successful.

**Comment by bttrx** [comment]
To make it work for ([bplaced freestyle](https://www.bplaced.net/freestyle "bplaced freestyle - Webspace & Webhosting")) I had to create this `.htaccess` file inside the `data/images/` folder:

```
<IfModule version_module>
  <IfVersion >= 2.4>
    Require all denied
    <FilesMatch "\.(gif|jpe?g|png|webp)$">
      Require all granted
    </FilesMatch>
  </IfVersion>
  <IfVersion < 2.4>
    Allow from none
    Deny from all
    <FilesMatch "\.(gif|jpe?g|png|webp)$">
      Allow from all
    </FilesMatch>
  </IfVersion>
</IfModule>

<IfModule !version_module>
    Require all denied
</IfModule> 
```

Unfortunately, even with this file in place I still get 403 for my other hoster Bitpalast. And testing is a little pain the a..., because security mechanisms always ban my IP address for some minutes after a few 403s.

**Comment by meerkatzenwildschein** [comment]
Thank you for sharing your experience. I hope it will be useful to others as well.
